services:
  db:
    image: mongo:8.0.13
    restart: unless-stopped
    ports:
      - "33000:27017"
  
  test-app:
    image: andretadeu/go-test-app:0.1.0
    ports:
      - "9980:8080"
    depends_on:
      - db